### ISSUE TITLE
Приложение падает с пустой командой

### ISSUE THREAD

**Issue by protoss-player** [gotohe11/get_issues#9]
**Шаги:**
1. Запустить приложение.
2. Нажать Enter в пустой командной строке.

**Результат:**
Падение с исключением:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/bios/get_issues/__main__.py", line 9, in <module>
    main()
  File "/home/bios/get_issues/__main__.py", line 5, in main
    cli.run()
  File "/home/bios/get_issues/cli.py", line 274, in run
    _run_one(user_command)
  File "/home/bios/get_issues/cli.py", line 250, in _run_one
    cmd = parts[0]
          ~~~~~^^^
IndexError: list index out of range
```

**Ожидается:**
Приложение снова предложит ввести команду.

**Comment by gotohe11** [comment]
have done
